<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);

$debug = false;

require_once (__DIR__ . '/inc/includes.php');

try {
	$db = Database::singleton();
} catch (Exception $e) {
	ErrorHandling::addError('Cannot access database. Make sure the MySQL server is running, or <a href="installer/" class="alert-link">create a new database</a>');
}

// SESSION handling
$session = Session::singleton(); // initialize both a PHP session and an Ampersand session as soon as we can.
if(isset($_REQUEST['resetSession'])){ // TODO: reset working not working properly. Refresh of page needed before reset has effect.
	$session->destroySession();	// unset $_SESSION variables and Ampersand SESSION atom
	unset($session); // delete Session object
	$session = Session::singleton(); // initialize new session
}

RuleEngine::checkRules($session->role->id);

?>
<!DOCTYPE html>
<!-- Generated by <?php echo $versionInfo ?> -->
<html>
	<head>
		<title><?php echo $dbName;?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Bootstrap -->
		<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
		
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta http-equiv="Pragma" content="no-cache">
		<meta http-equiv="no-cache">
		<meta http-equiv="Expires" content="-1">
		<meta http-equiv="cache-Control" content="no-cache"> 

		<link rel="apple-touch-icon-precomposed" href="images/AmpersandIcon.png">
		<link href="css/Ampersand2.css" rel="stylesheet" type="text/css"/>
		<link href="css/Custom.css" rel="stylesheet" type="text/css"/>
		<link href="css/tno.css" rel="stylesheet" media="screen">
		<link href="css/smoothness/jquery-ui-1.10.4.custom.css" rel="stylesheet" type="text/css"/>

		<script src="js/jquery-1.11.0.min.js"></script>
		<script src="js/jquery-ui-1.10.4.custom.js"></script>
		<script src="bootstrap/js/bootstrap.min.js"></script>
		<script src="js/Ampersand2.js"></script>
		<script src="js/jquery-migrate-1.2.1.js"></script>
	</head>
	<body onload="initialize()">
		
		<div class="navbar navbar-default navbar-fixed-top">
			<div class="tno">
				<div class="container">
					<img src="images/tnotimeline.png" alt="TNO" />
				</div>
			</div>
			<div class="container">
				<ul class="nav nav-pills">					
					<?php foreach($session->role->getInterfaces(true) as $interface) 
									echo '<li id="'.Viewer::escapeHtmlAttrStr($interface->name).'">' // the interface attribute is there so we can style specific menu items with css
										.'<a href="?interface='.Viewer::escapeHtmlAttrStr($interface->name).'&atom=1">'
										.'<span class="glyphicon glyphicon-list-alt"></span> '.htmlSpecialChars($interface->name).'</a>'
										.'</li>';
					?>
					
					<li class="dropdown pull-right">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-plus"></span></a>
						<ul class="dropdown-menu" role="menu">
						  <?php foreach($session->role->getInterfaces(false) as $interface) echo '<li><a href="?interface='.$interface->name.'&atom='.$interface->srcConcept.'_'.time().'">'.htmlSpecialChars($interface->srcConcept . ' (' . $interface->name . ')').'</a></li>';?>
						</ul>
					</li>
					
					<li class="dropdown pull-right">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span></a>
						<ul class="dropdown-menu" role="menu">
						  <?php  foreach(Role::getAllRoles() as $role) echo '<li><a href="?role='.$role->id.'">'.htmlSpecialChars($role->name).'</a></li>'; ?>
						</ul>
					</li>
					
					<?php if(isset($GLOBALS['apps'])){ ?>
						<li class="dropdown pull-right">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-th"></span></a>
							<ul class="dropdown-menu" role="menu">
							  <?php  foreach($GLOBALS['apps'] as $app) echo '<li><a href="'.$app['link'].'"><span class="'.$app['icon'].'"></span> '.htmlSpecialChars($app['name']).'</a></li>'; ?>
							</ul>
						</li>
					<?php } ?>
					
					
					<?php if(isset($GLOBALS['viewers'])){ ?>
						<li class="dropdown pull-right">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-eye-open"></span></a>
							<ul class="dropdown-menu" role="menu">
							  <?php  foreach($GLOBALS['viewers'] as $key => $viewer) echo '<li><a href="?viewer='.$key.'"><span class="'.$viewer['icon'].'"></span> '.htmlSpecialChars($viewer['name']).'</a></li>'; ?>
							</ul>
						</li>
					
					<?php } ?>
					
					<li id="installer" class="pull-right">
						<a href="installer.php"><span class="glyphicon glyphicon-trash"></span></a>
					</li>
					
					<li id="violations" class="pull-right">
						<a href="#"><span class="glyphicon glyphicon-bell"></span></a>
					</li>

				</ul>
			</div>
		</div>
		
		<div class="container mainview">
			<div id="errors">
				<?php
				foreach (ErrorHandling::getErrors() as $error){
				?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error!</strong> <?php echo $error;?>
				</div>
				<?php } ?>
			</div>
			<div id="invariants">
				<?php
				foreach (ErrorHandling::getInvariants() as $invariant){
				?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Invariant!</strong> <?php echo $invariant;?>
				</div>
				<?php } ?>
			</div>
			<div id="violations">
				<?php
				foreach (ErrorHandling::getViolations() as $violationMessage => $rows){
					$i++;
				?>
				<div class="panel panel-warning ">
					<div class="panel-heading btn btn-block" data-toggle="collapse" data-target="#violation<?php echo $i;?>">
						<div class="text-left"><strong>Violation!</strong> <?php echo $violationMessage;?></div>
					</div>
					<ul class="list-group collapse" id="violation<?php echo $i;?>">
						<?php foreach ($rows as $row) echo '<li class="list-group-item">'.$row.'</li>'; ?>
					</ul>
				</div>
				<?php } ?>
			</div>
			<div id="notifications">
				<?php
				foreach (ErrorHandling::getNotifications() as $notification){
				?>
				<div class="alert alert-info alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Notification!</strong> <?php echo $notification;?>
				</div>
				<?php } ?>
			</div>
			<div id="notifications">
				<?php
				foreach (ErrorHandling::getSuccesses() as $success){
				?>
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Success!</strong> <?php echo $success;?>
				</div>
				<?php } ?>
			</div>
			
			<?php
		
			print $session->viewer->getView();
		
			?>
		</div>
		
		<script src="plugins/statusColors/js/statusColors.js"></script>
	</body>
</html>