<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);

$debug = false;

require_once (__DIR__ . '/inc/includes.php');

try {
	$db = Database::singleton();
} catch (Exception $e) {
	ErrorHandling::addError('Cannot access database. Make sure the MySQL server is running, or <a href="installer/" class="alert-link">create a new database</a>');
}

// SESSION handling
$session = Session::singleton(); // initialize both a PHP session and an Ampersand session as soon as we can.
if(isset($_REQUEST['resetSession'])){ // TODO: reset working not working properly. Refresh of page needed before reset has effect.
	$session->destroySession();	// unset $_SESSION variables and Ampersand SESSION atom
	$session = Session::singleton(); // initialize new session
}

RuleEngine::checkRules($session->role->id);

?>
<!DOCTYPE html>
<!-- Generated by <?php echo $versionInfo ?> -->
<html>
	<?php echo $session->viewer->getHtmlHead();?>
	
	<body onload="initialize(); $('.tooltip-to-be-initialized').toggleClass('tooltip-to-be-initialized').tooltip();">
		
				
		<div class="container mainview">
			<div id="errors">
				<?php
				foreach (ErrorHandling::getErrors() as $error){
				?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Error!</strong> <?php echo $error;?>
				</div>
				<?php } ?>
			</div>
			<div id="invariants">
				<?php
				foreach (ErrorHandling::getInvariants() as $invariant){
				?>
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Invariant!</strong> <?php echo $invariant;?>
				</div>
				<?php } ?>
			</div>
			<div id="violations">
				<?php
				foreach (ErrorHandling::getViolations() as $violationMessage => $rows){
					$i++;
				?>
				<div class="panel panel-warning ">
					<div class="panel-heading btn btn-block" data-toggle="collapse" data-target="#violation<?php echo $i;?>">
						<div class="text-left"><strong>Violation!</strong> <?php echo $violationMessage;?></div>
					</div>
					<ul class="list-group collapse" id="violation<?php echo $i;?>">
						<?php foreach ($rows as $row) echo '<li class="list-group-item">'.$row.'</li>'; ?>
					</ul>
				</div>
				<script>$('.messageIndicator').css('color', 'orange');</script>
				<?php } ?>
			</div>
			<div id="notifications" class="hidden">
				<?php
				foreach (ErrorHandling::getNotifications() as $notification){
				?>
				<div class="alert alert-info alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Notification!</strong> <?php echo $notification;?>
				</div>
				<?php } ?>
			</div>
			<div id=successes>
				<?php
				foreach (ErrorHandling::getSuccesses() as $success){
				?>
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Success!</strong> <?php echo $success;?>
				</div>
				<?php } ?>
			</div>
			
			<?php
		
			print $session->viewer->getHtmlBody();
		
			?>
		</div>
		<script src="extensions/statusColors/js/statusColors.js"></script>
	</body>
</html>