---
  cache:
    - '%APPDATA%\cabal'
    - '%APPDATA%\ghc'
    - '%APPDATA%\stack'
  
  install:
    - choco install ghc --version 8.2.2
    - choco install haskell-stack
    - refreshenv
    - cabal update
    - cabal install happy --overwrite-policy=always
  
  # perform the typical stack build, and also install the 
  # ampersand.exe file that we will mark as an artifact
  build_script:
    # Suppress output from stack setup, as there is a lot and it's not necessary.
    - stack setup --no-terminal > nul
    - stack build --only-snapshot --no-terminal
    - stack --local-bin-path . install ampersand
  # Set a magical environment variable
    - cmd: for /f %%i in ('stack exec ampersand -- -v') do set AMPERSAND_VERSION=%%i
    - cmd: pwd
    - cmd: where ampersand
    - cmd: where stack
  # mark the file(s) as an artifact; this means AppVeyor will hang on to it after the build completes:
  artifacts:
    - path: ampersand.exe
      name: Windows_binary

  # Auto-deploy
  # specify that, for each build that completes, AppVeyor 
  # should push a release with the right tag to 
  # the GitHub releases page! 
  # We only release when the branch == master.
  # (Note: probably we would want to be a bit more 
  # elaborate about when we push to the releases page; making sure 
  # that we include proper release notes, etc.)
  deploy:
    - provider: GitHub
      tag: '$(AMPERSAND_VERSION)'
      release: '$(AMPERSAND_VERSION)'
      auth_token:
        secure: B9wxH2Me3jIbEn9xlvIY9SEWdELRgKMtEZeQZmJQm5wMGjp4YF4wQmAHCy3ofTJG
      artifact: Windows_binary
      on:
        branch: master  
  