# Example inspired by https://hub.zhox.com/posts/chocolatey-introduction/

clone_folder: "c:\\WORK"

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR --http-transport=plain-http"
  matrix:
    # 64 bit builds
    - GHCVER: "8.6.2"
      CHOCOPTS:
    # 32 bit builds --disabled, because pandoc fails to build at 32 bit.
    # - GHCVER: "8.4.2"
    #   CHOCOPTS: --forcex86


cache:
- "C:\\SR"

install:
 - "choco install -y ghc --version %GHCVER% %CHOCOPTS%"
 - "choco install -y cabal %CHOCOPTS%"
 - "refreshenv"
 - "set PATH=C:\\ghc\\ghc-%GHCVER%:C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
 - "cabal --version"
 - "ghc --version"
 - "cabal %CABOPTS% new-update -v"

build: off

test_script:
 - IF EXIST configure.ac bash -c "autoreconf -i"
 - "echo packages:. > cabal.project"
 - "cabal %CABOPTS% new-install exe:ampersand -j1"
 
# perform the typical stack build, and also install the 
# ampersand.exe file that we will mark as an artifact
build_script:
# Run weeder, to check that there are no weeds (see https://github.com/ndmitchell/weeder )
# - stack install weeder --resolver=nightly
# - weeder --version
# - weeder . --build
### - ps: Invoke-Command ([Scriptblock]::Create((Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/weeder/master/misc/appveyor.ps1').Content)) -ArgumentList @('--version')
### - ps: Invoke-Command ([Scriptblock]::Create((Invoke-WebRequest 'https://raw.githubusercontent.com/ndmitchell/weeder/master/misc/appveyor.ps1').Content)) -ArgumentList @('. --build')

# Set a magical environment variable
- cmd: for /f %%i in ('ampersand -v') do set AMPERSAND_VERSION=%%i

# mark the file(s) as an artifact; this means AppVeyor will hang on to it after the build completes:
artifacts:
  - path: ampersand.exe
    name: Windows_ampersand_binary
  - path: ampPreProc.exe
    name: Windows_preprocessor_binary

# Auto-deploy
# specify that, for each build from a tag, we add the windows
# artifacts.
deploy:
  - provider: GitHub
    auth_token:
      secure: B9wxH2Me3jIbEn9xlvIY9SEWdELRgKMtEZeQZmJQm5wMGjp4YF4wQmAHCy3ofTJG
    artifact: Windows_ampersand_binary, Windows_preprocessor_binary
    on:
      appveyor_repo_tag: true        # deploy on tag push only
