name:           ampersand
version:        4.0.0
author:         Stef Joosten
maintainer:     stef.joosten@ou.nl
synopsis:       Toolsuite for automated design of enterprise information systems.
description:    You can define your business processes by means of rules, written in Relation Algebra.
homepage:       http://ampersandtarski.github.io/
category:       Database Design
stability:      alpha
tested-with:    GHC == 8.6.5
build-type:     Custom
license:        GPL
license-file:   LICENSE
copyright:      Stef Joosten
bug-reports:    https://github.com/AmpersandTarski/ampersand/issues
extra-source-files:
      - LICENSE
      - ReleaseNotes.md
      - AmpersandData/FormalAmpersand/*
      - AmpersandData/PrototypeContext/*
      - outputTemplates/*
      - testing/**/*

ghc-options: 
      - -Wall
      - -Wcompat
      - -Widentities
      # TODO: Remove this option once https://github.com/haskell/cabal/issues/4739 is fixed
      - -optP-Wno-nonportable-include-path  # Workaround, See issue #937
#      - -Wincomplete-record-updates
#      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
default-extensions: 
      - NoImplicitPrelude
dependencies:
      - aeson == 1.4.*
      - aeson-pretty == 0.8.*
      - ansi-terminal == 0.9.*
      - base == 4.12.*
      - bytestring == 0.10.*
      - conduit == 1.3.*
      - containers == 0.6.*
      - data-default == 0.7.*
      - directory == 1.3.*
      - doctemplates == 0.8.*
      - extra >= 1.6.6
      - filepath == 1.4.*
      - fsnotify == 0.3.*
      - generic-deriving
      - graphviz == 2999.20.*
      - hashable == 1.2.*
      - HStringTemplate == 0.8.*
      - http-conduit == 2.3.*
      - hxt == 9.3.*
      - lens == 4.17.*
      - mtl == 2.2.*
      - optparse-applicative == 0.14.*
      - pandoc == 2.9.*
      - pandoc-crossref == 0.3.6.1
      - pandoc-types == 1.20.*
      - parsec == 3.1.*
      - process == 1.6.*
      - QuickCheck == 2.13.*
      - rio == 0.1.*
      - simple-sql-parser == 0.4.4
      - split == 0.2.*
      - SpreadsheetML == 0.1.*
      - terminal-size == 0.3.*
      - texmath == 0.12.*
      - text == 1.2.*
      - time == 1.8.*
      - transformers
      - typed-process == 0.2.*
      - wl-pprint == 1.2.* 
      - xlsx == 0.7.*
      - yaml == 0.11.*
      - yaml-config == 0.4.*
      - zip-archive >= 0.4.1
when:
  - condition: os(windows)
    then:
        dependencies: Win32
    else:
        dependencies: unix

library:
  source-dirs: 
      - src/
  exposed-modules:
      - Ampersand
      - Ampersand.ADL1
      - Ampersand.ADL1.Disambiguate
      - Ampersand.ADL1.Expression
      - Ampersand.ADL1.Lattices
      - Ampersand.ADL1.P2A_Converters
      - Ampersand.ADL1.PrettyPrinters
      - Ampersand.ADL1.Rule
      - Ampersand.Basics
      - Ampersand.Basics.Auxiliaries
      - Ampersand.Basics.Exit
      - Ampersand.Basics.Languages
      - Ampersand.Basics.PandocExtended
      - Ampersand.Basics.Prelude
      - Ampersand.Basics.String
      - Ampersand.Basics.Unique
      - Ampersand.Basics.Version
      - Ampersand.Classes
      - Ampersand.Classes.ConceptStructure
      - Ampersand.Classes.Relational
      - Ampersand.Classes.ViewPoint
      - Ampersand.Core.A2P_Converters
      - Ampersand.Core.AbstractSyntaxTree
      - Ampersand.Core.ParseTree
      - Ampersand.Core.ShowAStruct
      - Ampersand.Core.ShowPStruct
      - Ampersand.FSpec
      - Ampersand.FSpec.Crud
#      - Ampersand.FSpec.FPA
      - Ampersand.FSpec.FSpec
      - Ampersand.FSpec.FSpecAux
      - Ampersand.FSpec.GenerateUML
      - Ampersand.FSpec.Motivations
      - Ampersand.FSpec.SQL
      - Ampersand.FSpec.ShowHS
      - Ampersand.FSpec.ShowMeatGrinder
      - Ampersand.FSpec.MetaModels
      - Ampersand.FSpec.ToFSpec.ADL2FSpec
      - Ampersand.FSpec.ToFSpec.ADL2Plug
      - Ampersand.FSpec.ToFSpec.Calc
      - Ampersand.FSpec.ToFSpec.CreateFspec
      - Ampersand.FSpec.ToFSpec.NormalForms
      - Ampersand.FSpec.ToFSpec.Populated
      - Ampersand.FSpec.Transformers
      - Ampersand.Graphic.ClassDiag2Dot
      - Ampersand.Graphic.ClassDiagram
      - Ampersand.Graphic.Fspec2ClassDiagrams
      - Ampersand.Graphic.Graphics
      - Ampersand.Input
      - Ampersand.Input.ADL1.CtxError
      - Ampersand.Input.ADL1.FilePos
      - Ampersand.Input.ADL1.Lexer
      - Ampersand.Input.ADL1.LexerMessage
      - Ampersand.Input.ADL1.LexerMonad
      - Ampersand.Input.ADL1.LexerTexts
      - Ampersand.Input.ADL1.LexerToken
      - Ampersand.Input.ADL1.Parser
      - Ampersand.Input.ADL1.ParsingLib
      - Ampersand.Input.Parsing
      - Ampersand.Input.PreProcessor
      - Ampersand.Input.Xslx.XLSX
      - Ampersand.Misc.Commands
      - Ampersand.Misc.HasClasses
      - Ampersand.Options.GlobalParser
      - Ampersand.Options.LogLevelParser
      - Ampersand.Options.Utils
      - Ampersand.Output
      - Ampersand.Output.FSpec2Pandoc
      - Ampersand.Output.FSpec2SQL
      - Ampersand.Output.PandocAux
      - Ampersand.Output.Population2Xlsx
#      - Ampersand.Output.PredLogic
#      - Ampersand.Output.Statistics
      - Ampersand.Output.ToJSON.Concepts
      - Ampersand.Output.ToJSON.Conjuncts
      - Ampersand.Output.ToJSON.Interfaces
      - Ampersand.Output.ToJSON.JSONutils
      - Ampersand.Output.ToJSON.Populations
      - Ampersand.Output.ToJSON.Relations
      - Ampersand.Output.ToJSON.Roles
      - Ampersand.Output.ToJSON.Rules
      - Ampersand.Output.ToJSON.Settings
      - Ampersand.Output.ToJSON.ToJson
      - Ampersand.Output.ToJSON.Views
      - Ampersand.Output.ToPandoc
      - Ampersand.Output.ToPandoc.ChapterConceptualAnalysis
      - Ampersand.Output.ToPandoc.ChapterDataAnalysis
      - Ampersand.Output.ToPandoc.ChapterDiagnosis
      - Ampersand.Output.ToPandoc.ChapterIntroduction
      - Ampersand.Output.ToPandoc.ChapterNatLangReqs
      - Ampersand.Output.ToPandoc.SharedAmongChapters
      - Ampersand.Prototype.GenFrontend
      - Ampersand.Prototype.PHP
      - Ampersand.Prototype.ProtoUtil
      - Ampersand.Prototype.TableSpec
      - Ampersand.Prototype.ValidateSQL
      - Ampersand.Runners
      - Ampersand.Test
      - Ampersand.Test.Parser.ArbitraryTree
      - Ampersand.Test.Parser.ParserTest
      - Ampersand.Test.Parser.QuickChecks
      - Ampersand.Test.Regression
#      - Ampersand.Test.RunAmpersand
      - Ampersand.Test.TestScripts
      - MainApps
      - Options.Applicative.Builder.Extra
  generated-exposed-modules:
      - Ampersand.Basics.BuildInfo_Generated
      - Ampersand.Prototype.StaticFiles_Generated
custom-setup:
  dependencies:
      - base == 4.12.*
      - bytestring == 0.10.*
      - Cabal == 2.4.*
      - directory == 1.3.*
      - filepath == 1.4.*
      - process == 1.6.*
      - rio == 0.1.*
      - time == 1.8.*
      - zip-archive >= 0.4.1

executables:
  ampersand:
    source-dirs: 
      - app/Ampersand
    main: Main.hs
    ghc-options:
      - -threaded
    dependencies: 
      - ampersand
      - Cabal == 2.4.*
      

  ampPreProc:
    source-dirs: 
      - app/AmpPreProc
    main: Main.hs
    ghc-options: 
      - -threaded
    dependencies: 
      ampersand
    when:
      - condition: ! '!(flag(buildAll))'
        buildable: false

tests:
  ampersand-test:
    main: Main.hs
    source-dirs: app/Test
    ghc-options: 
      - -threaded
    dependencies: 
      ampersand

flags:
  buildAll:
    description: Build both ampersand and ampPreProc.
    default:     false 
    manual:      true

