name: ampersand
version: 5.4.11
author: Stef Joosten
maintainer: stef.joosten@ou.nl
synopsis: Toolsuite for automated design of enterprise information systems.
description: You can define your business processes by means of rules, written in Relation Algebra.
homepage: http://ampersandtarski.github.io/
category: Database Design
stability: beta
tested-with: GHC == 9.6.6
build-type: Custom
license: GPL
license-file: LICENSE
copyright: Stef Joosten
bug-reports: https://github.com/AmpersandTarski/ampersand/issues
extra-source-files:
  - LICENSE
  - ReleaseNotes.md
  - AmpersandData/FormalAmpersand/*
  - AmpersandData/PrototypeContext/*
  - outputTemplates/*
  - testing/**/*

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # TODO: Remove this option once https://github.com/haskell/cabal/issues/4739 is fixed
  - -optP-Wno-nonportable-include-path # Workaround, See issue #937
  #      - -Wincomplete-record-updates
  #      - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fwrite-ide-info
  - -hiedir=.hie
#  - -Wint-conversion # added in the hope to get hexpat working again on macOS
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
dependencies:
  ## Note: We rely on stackage to supply the right versions. The set of versions is determined by the resolver in `stack.yaml`
  - aeson
  - aeson-pretty
  - ansi-terminal
  - base
  # - bytestring
  - casing
  - conduit
  - containers
  - cryptonite
  - data-default
  - directory
  - doctemplates
  - extra
  - filepath
  - fsnotify
  - generic-deriving
  - graphviz
  - hashable
  - HStringTemplate
  # - http-conduit
  - hxt
  - lens
  - mtl
  - optparse-applicative
  - pandoc
  - pandoc-crossref
  - pandoc-types
  - parsec
  # - prettyprinter
  # - prettyprinter-ansi-terminal
  - process
  - QuickCheck
  - quickcheck-instances
  - rdf4h
  - rio
  # - salve
  - simple-sql-parser
  # - split
  - terminal-size
  # - texmath
  - text
  - text1
  - time
  - transformers
  # - typed-process
  - uri-encode
  - wl-pprint # to be replaced with prettyprinter stuff
  - xlsx
  - yaml
  - zip-archive
when:
  - condition: os(windows)
    then:
      dependencies: Win32
    else:
      dependencies: unix

library:
  source-dirs:
    - src/
  exposed-modules:
    - Ampersand
    - Ampersand.ADL1
    - Ampersand.ADL1.Disambiguate
    - Ampersand.ADL1.Expression
    - Ampersand.ADL1.Lattices
    - Ampersand.ADL1.P2A_Converters
    - Ampersand.ADL1.PrettyPrinters
    - Ampersand.ADL1.Rule
    - Ampersand.Basics
    - Ampersand.Basics.Auxiliaries
    - Ampersand.Basics.Exit
    - Ampersand.Basics.Languages
    - Ampersand.Basics.PandocExtended
    - Ampersand.Basics.Prelude
    - Ampersand.Basics.String
    - Ampersand.Basics.Unique
    - Ampersand.Basics.Version
    - Ampersand.Classes
    - Ampersand.Classes.ConceptStructure
    - Ampersand.Classes.Relational
    - Ampersand.Classes.ViewPoint
    - Ampersand.Core.A2P_Converters
    - Ampersand.Core.AbstractSyntaxTree
    - Ampersand.Core.ParseTree
    - Ampersand.Core.ShowAStruct
    - Ampersand.Core.ShowPStruct
    - Ampersand.FSpec
    - Ampersand.FSpec.Crud
    - Ampersand.FSpec.FSpec
    - Ampersand.FSpec.FSpecAux
    - Ampersand.FSpec.Motivations
    - Ampersand.FSpec.SQL
    - Ampersand.FSpec.ShowHS
    - Ampersand.FSpec.ToFSpec.ADL2FSpec
    - Ampersand.FSpec.ToFSpec.ADL2Plug
    - Ampersand.FSpec.ToFSpec.Calc
    - Ampersand.FSpec.ToFSpec.CreateFspec
    - Ampersand.FSpec.ToFSpec.NormalForms
    - Ampersand.FSpec.ToFSpec.Populated
    - Ampersand.FSpec.Transformers
    - Ampersand.Graphic.ClassDiag2Dot
    - Ampersand.Graphic.ClassDiagram
    - Ampersand.Graphic.Fspec2ClassDiagrams
    - Ampersand.Graphic.Graphics
    - Ampersand.Input
    - Ampersand.Input.ADL1.CtxError
    - Ampersand.Input.ADL1.FilePos
    - Ampersand.Input.ADL1.Lexer
    - Ampersand.Input.ADL1.LexerMessage
    - Ampersand.Input.ADL1.LexerMonad
    - Ampersand.Input.ADL1.LexerTexts
    - Ampersand.Input.ADL1.LexerToken
    - Ampersand.Input.ADL1.Parser
    - Ampersand.Input.ADL1.ParsingLib
    - Ampersand.Input.Parsing
    - Ampersand.Input.PreProcessor
    - Ampersand.Input.Xslx.XLSX
    - Ampersand.Misc.Commands
    - Ampersand.Misc.HasClasses
    - Ampersand.Options.GlobalParser
    - Ampersand.Options.LogLevelParser
    - Ampersand.Options.Utils
    - Ampersand.Output
    - Ampersand.Output.FSpec2Pandoc
    - Ampersand.Output.FSpec2SQL
    - Ampersand.Output.PandocAux
    - Ampersand.Output.Population2Xlsx
    - Ampersand.Output.ToJSON.Concepts
    - Ampersand.Output.ToJSON.Conjuncts
    - Ampersand.Output.ToJSON.Interfaces
    - Ampersand.Output.ToJSON.JSONutils
    - Ampersand.Output.ToJSON.Populations
    - Ampersand.Output.ToJSON.Relations
    - Ampersand.Output.ToJSON.Roles
    - Ampersand.Output.ToJSON.Rules
    - Ampersand.Output.ToJSON.Settings
    - Ampersand.Output.ToJSON.ToJson
    - Ampersand.Output.ToJSON.Views
    - Ampersand.Output.ToPandoc
    - Ampersand.Output.ToPandoc.ChapterConceptualAnalysis
    - Ampersand.Output.ToPandoc.ChapterDataAnalysis
    - Ampersand.Output.ToPandoc.ChapterDiagnosis
    - Ampersand.Output.ToPandoc.ChapterIntroduction
    - Ampersand.Output.ToPandoc.ChapterNatLangReqs
    - Ampersand.Output.ToPandoc.SharedAmongChapters
    - Ampersand.Prototype.GenAngularFrontend
    - Ampersand.Prototype.GenBackend
    - Ampersand.Prototype.GenFrontend
    - Ampersand.Prototype.PHP
    - Ampersand.Prototype.ProtoUtil
    - Ampersand.Prototype.TableSpec
    - Ampersand.Prototype.ValidateSQL
    - Ampersand.Runners
    - Ampersand.Test
    - Ampersand.Test.Parser.ArbitraryTree
    - Ampersand.Test.Parser.ParserTest
    - Ampersand.Test.Parser.QuickChecks
    - Ampersand.Test.Regression
    - MainApps
    - Options.Applicative.Builder.Extra
  generated-exposed-modules:
    - Ampersand.Basics.BuildInfo_Generated
    - Ampersand.Prototype.StaticFiles_Generated
custom-setup:
  dependencies:
    ## Note: We rely on stackage to supply the right versions. The set of versions is determined by the resolver in `stack.yaml`
    - base
    - bytestring
    - Cabal
    - directory
    - filepath
    - hexpat
    - process
    - rio
    - time
    - salve
    - zip-archive

executables:
  ampersand:
    source-dirs:
      - app/Ampersand
    main: Main.hs
    ghc-options:
      - -threaded
      - -fwrite-ide-info
    dependencies:
      - ampersand
      - Cabal

  ampPreProc:
    source-dirs:
      - app/AmpPreProc
    main: Main.hs
    ghc-options:
      - -threaded
    dependencies: ampersand
    when:
      - condition: ! "!(flag(buildAll))"
        buildable: false

tests:
  ampersand-test:
    main: Main.hs
    source-dirs: app/Test
    ghc-options:
      - -threaded
    dependencies: ampersand

flags:
  buildAll:
    description: Build both ampersand and ampPreProc.
    default: false
    manual: true
