{-# LANGUAGE TemplateHaskell, GeneralizedNewtypeDeriving, Rank2Types, NoMonomorphismRestriction, ScopedTypeVariables #-}

module Database.Design.Ampersand.Test.Parser.ParseScripts (testScripts, scripts) where

import Database.Design.Ampersand.Test.Parser.ParserTest
import System.Directory
import Control.Monad

-- Tries to parse all the given files
testScripts :: [FilePath] -> IO Bool
testScripts [] = return True
testScripts fs =
    do parsed <- parseFile (head fs)
       if parsed then testScripts (tail fs)
       else return False

endswith :: String -> String -> Bool
endswith a b = (drop (length a - length b) a) == b

-- Returns tuple with files and subdirectories inside the given directory
getDirectory :: FilePath -> IO ([FilePath],[FilePath])
getDirectory path =
    do contents <- getDirectoryContents path
       let valid = filter (\x-> x /= "." && x /= "..") contents
       let paths = map ((++) path) valid
       files <- filterM doesFileExist paths
       subdirs <- filterM doesDirectoryExist paths
       return (files, subdirs)

getFiles :: String -> FilePath -> IO [FilePath]
getFiles ext dir =
    do (fs, ds) <- getDirectory (dir++"/")
       let files = filter (\f->f `endswith` ext) fs
       foldM recursive files ds
      where recursive rs d =
                do ms <- getFiles ext d
                   return $ ms ++ rs

models :: [FilePath]
models = [
        "../ampersand-models/Arbeidsduur/Stef's demo van Arbeidsduur.adl",
        "../ampersand-models/Arbeidsduur/Arbeidsduur.adl",
        "../ampersand-models/Archimate1/ArchiSurance2.adl",
        "../ampersand-models/Archimate1/ArchiSurance.adl",
        "../ampersand-models/Archimate1/Archimate1.adl",
        "../ampersand-models/ArticleTests/phone.adl",
        "../ampersand-models/ASR NGA/ManagementInformatie.adl",
        "../ampersand-models/ASR NGA/Demo.adl",
        "../ampersand-models/Atlasv2/RepoRap/RAP.adl",
        "../ampersand-models/Atlasv2/RepoRap/Fspec.adl",
        "../ampersand-models/Atlasv2/RepoRap/AST.adl",
        "../ampersand-models/Atlasv2/RepoRap/admin_interfaces.adl",
        "../ampersand-models/BIV/ounlschermen.adl",
        "../ampersand-models/Bugs/Current/Other/Bug335_Kl0Kl1.adl",
        "../ampersand-models/Bugs/Current/SQL/ARM20-Test8.adl",
        "../ampersand-models/Bugs/Current/SQLFail/Bug331_TotalInjective.adl",
        "../ampersand-models/Bugs/Current/SQLFail/Bug302_IgnoredV.adl",
        "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/WBP-Ontologie.adl",
        "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/WBP-Glossary.adl",
        "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/SystemStuff.adl",
        "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/RuntimeStuff.adl",
        "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/RETINABUG.adl",
        "../ampersand-models/Bugs/Fixed/Other/Bug_GeneratedTables.adl",
        "../ampersand-models/Bugs/Fixed/Other/Bug_ColumnProperties.adl",
        "../ampersand-models/Bugs/Fixed/SQL/Bug_Totality.adl",
        "../ampersand-models/Bugs/Fixed/SQL/Bug_SingletonExpression.adl",
        "../ampersand-models/Bugs/Fixed/SQL/Bug_RelAdd.adl",
        "../ampersand-models/Bugs/Fixed/SQL/Bug_HaskellViolationTest.adl",
        "../ampersand-models/Bugs/No Sentinel/TechDataModelTest.adl",
        "../ampersand-models/Bugs/No Sentinel/Bug434.adl",
        "../ampersand-models/Bugs/No Sentinel/Bug337_FatalONE.adl",
        "../ampersand-models/CP23/CP23.adl",
        "../ampersand-models/CP23/CP23 Status.adl",
        "../ampersand-models/CP23/CP23 Population.adl",
        "../ampersand-models/CP23/CP23 Ontology.adl",
        "../ampersand-models/CP23/CP23 Interfaces.adl",
        "../ampersand-models/Delivery/IdentiSample.adl",
        "../ampersand-models/Delivery/DeliverySessions.adl",
        "../ampersand-models/Delivery/DeliveryRieksObl.adl",
        "../ampersand-models/Delivery/DeliveryRieksNoObl.adl",
        "../ampersand-models/Delivery/DeliveryAccounts.adl",
        "../ampersand-models/Delivery/Delivery.adl",
        "../ampersand-models/EURent/EURent.adl",
        "../ampersand-models/EURent/EURent WEBSITE interface.adl",
        "../ampersand-models/EURent/EURent Population.adl",
        "../ampersand-models/EURent/EURent Ontology.adl",
        "../ampersand-models/EURent/EURent Interfaces.adl",
        "../ampersand-models/EURent/EURent Documentation.adl",
        "../ampersand-models/EURent/EURent Computations.adl",
        "../ampersand-models/EURent/EURent BRANCH interface.adl",
        "../ampersand-models/FPA/FPATest.adl",
        "../ampersand-models/Generics/GenericYesNo.adl",
        "../ampersand-models/Generics/GenericTransitiveClosure.adl",
        "../ampersand-models/Generics/GenericSessionAccounts.adl",
        "../ampersand-models/Generics/Generics.adl",
        "../ampersand-models/Generics/GenericMessaging.adl",
        "../ampersand-models/Generics/GenericDateTime.adl",
        "../ampersand-models/HRM/HRM.adl",
        "../ampersand-models/HRM/HRM Status.adl",
        "../ampersand-models/HRM/HRM Population.adl",
        "../ampersand-models/HRM/HRM Ontology.adl",
        "../ampersand-models/HRM/HRM Interfaces.adl",
        "../ampersand-models/IDEA/GBA.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/wettelijkeTaken.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/Producten.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/Gebeurtenissen.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/BusinessServicesSJ0.22.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/BusinessInterfaces.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/versies/Taken.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/versies/RfPtje.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/versies/PopRegelgeving.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/wetsteksten.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/VIROarch.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/Populaties.adl",
        "../ampersand-models/INDOORS/overzichten/uitgangsscripts/Handelingen.adl",
        "../ampersand-models/INDOORS/overzichten/Overzichten.adl",
        "../ampersand-models/INDOORS/VerzoekschriftFamiliezaken.adl",
        "../ampersand-models/INDOORS/Oproepen.adl",
        "../ampersand-models/INDOORS/Gebeurtenis.adl",
        "../ampersand-models/INDOORS/DemoLamicieCode105.adl",
        "../ampersand-models/INDOORS/BerichtDefinitie.adl",
        "../ampersand-models/Inspectie OCW/OCWdemo/Voorschriften.adl",
        "../ampersand-models/Inspectie OCW/OCWdemo/Bevoegde_gezagen_basisonderwijs.adl",
        "../ampersand-models/Inspectie OCW/OCWdemo/batenlasten.adl",
        "../ampersand-models/Inspectie OCW/OCWdemo/basisonderwijs.adl",
        "../ampersand-models/ISAtest/SpecEdit.adl",
        "../ampersand-models/ISAtest/ISAtest2.adl",
        "../ampersand-models/ISAtest/ISAtest1.adl",
        "../ampersand-models/ISTAR/ISTAR.adl",
        "../ampersand-models/ISTAR/ISTAR-Workshop.adl",
        "../ampersand-models/ISTAR/GenericDataTypes.adl",
        "../ampersand-models/Koppelvlakken/InfoDomains.adl",
        "../ampersand-models/Koppelvlakken/DEMO_Koppelvlakken.adl",
        "../ampersand-models/Koppelvlakken/CoI.adl",
        "../ampersand-models/Misc/Kernmodel.adl",
        "../ampersand-models/Misc/Hello.adl",
        "../ampersand-models/Misc/FraakTest2.adl",
        "../ampersand-models/Misc/FraakTest1.adl",
        "../ampersand-models/Misc/ARM20-Test8.adl",
        "../ampersand-models/Misc/ARM20-Test7.adl",
        "../ampersand-models/Misc/ARM20-Test6.adl",
        "../ampersand-models/Misc/ARM20-Test5.adl",
        "../ampersand-models/Misc/ARM20-Test4.adl",
        "../ampersand-models/Misc/ARM20-Test3.adl",
        "../ampersand-models/Misc/ARM20-Test2.adl",
        "../ampersand-models/Misc/ARM20-Test1.adl",
        "../ampersand-models/Misc/ARM-Test2.adl",
        "../ampersand-models/Misc/ARM-Test1.adl",
        "../ampersand-models/Misc/ArchiTest5.adl",
        "../ampersand-models/Misc/ArchiTest4.adl",
        "../ampersand-models/Misc/ArchiTest3.adl",
        "../ampersand-models/Misc/ArchiTest1.adl",
        "../ampersand-models/Misc/Arbeidsduur.adl",
        "../ampersand-models/NVWA DTV/Uurtijdvakken.adl",
        "../ampersand-models/NVWA DTV/Urenpools.adl",
        "../ampersand-models/NVWA DTV/ToelageBerekeningen.adl",
        "../ampersand-models/NVWA DTV/Tijdverantwoordingen.adl",
        "../ampersand-models/NVWA DTV/SPIN.adl",
        "../ampersand-models/NVWA DTV/Resultaten.adl",
        "../ampersand-models/NVWA DTV/PopForTesting.adl",
        "../ampersand-models/NVWA DTV/Periodeverantwoordingen.adl",
        "../ampersand-models/NVWA DTV/Pcodes.adl",
        "../ampersand-models/NVWA DTV/OnregelmatigeDiensten.adl",
        "../ampersand-models/NVWA DTV/Onderbrekingen.adl",
        "../ampersand-models/NVWA DTV/Login.adl",
        "../ampersand-models/NVWA DTV/Kennismotor.adl",
        "../ampersand-models/NVWA DTV/expTijdsduur.adl",
        "../ampersand-models/NVWA DTV/DTV.adl",
        "../ampersand-models/RAPRelatedPatterns/Steigerwerk/BPM.adl",
        "../ampersand-models/RAPRelatedPatterns/UIservices.adl",
        "../ampersand-models/RAPRelatedPatterns/Identifiers2012.adl",
        "../ampersand-models/ServiceDesk/case.adl",
        "../ampersand-models/Session/Session.adl",
        "../ampersand-models/Simple/DeliverySimpleOPA.adl",
        "../ampersand-models/Simple/DeliverySimple.adl",
        "../ampersand-models/Simple/Delivery.adl",
        "../ampersand-models/Tests/NoSentinel/Multiplicities.adl",
        "../ampersand-models/Tests/ShouldFail/tryRieks.adl",
        "../ampersand-models/Tests/ShouldFail/try9.adl",
        "../ampersand-models/Tests/ShouldFail/Try49.adl",
        "../ampersand-models/Tests/ShouldFail/Try48.adl",
        "../ampersand-models/Tests/ShouldFail/try46.adl",
        "../ampersand-models/Tests/ShouldFail/Try44.adl",
        "../ampersand-models/Tests/ShouldFail/try4.adl",
        "../ampersand-models/Tests/ShouldFail/Try34.adl",
        "../ampersand-models/Tests/ShouldFail/try22b.adl",
        "../ampersand-models/Tests/ShouldFail/try22.adl",
        "../ampersand-models/Tests/ShouldFail/try17b.adl",
        "../ampersand-models/Tests/ShouldFail/try12.adl",
        "../ampersand-models/Tests/ShouldFail/Try10.adl",
        "../ampersand-models/Tests/ShouldFail/Try1.adl",
        "../ampersand-models/Tests/ShouldFail/SpecEdit.adl",
        "../ampersand-models/Tests/ShouldFail/Session.adl",
        "../ampersand-models/Tests/ShouldFail/RuleNamesMustBeUnique.adl",
        "../ampersand-models/Tests/ShouldFail/InterfaceTest1.adl",
        "../ampersand-models/Tests/ShouldFail/DuplicateInterfaces.adl",
        "../ampersand-models/Tests/ShouldFail/DoubleLabel.adl",
        "../ampersand-models/Tests/ShouldFail/ARM20-Test2wrong.adl",
        "../ampersand-models/Tests/ShouldFail/443_InterfaceRefType.adl",
        "../ampersand-models/Tests/ShouldSucceed/try9.adl",
        "../ampersand-models/Tests/ShouldSucceed/try6.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try52.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try51.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try50.adl",
        "../ampersand-models/Tests/ShouldSucceed/try5.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try46.adl",
        "../ampersand-models/Tests/ShouldSucceed/try45.adl",
        "../ampersand-models/Tests/ShouldSucceed/try43a.adl",
        "../ampersand-models/Tests/ShouldSucceed/try42.adl",
        "../ampersand-models/Tests/ShouldSucceed/try41a.adl",
        "../ampersand-models/Tests/ShouldSucceed/try41.adl",
        "../ampersand-models/Tests/ShouldSucceed/try40.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try39.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try38.adl",
        "../ampersand-models/Tests/ShouldSucceed/try37.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try35.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try34.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try33.adl",
        "../ampersand-models/Tests/ShouldSucceed/Try32.adl",
        "../ampersand-models/Tests/ShouldSucceed/try31.adl",
        "../ampersand-models/Tests/ShouldSucceed/try30.adl",
        "../ampersand-models/Tests/ShouldSucceed/try29.adl",
        "../ampersand-models/Tests/ShouldSucceed/try28.adl",
        "../ampersand-models/Tests/ShouldSucceed/try22.adl",
        "../ampersand-models/Tests/ShouldSucceed/try21.adl",
        "../ampersand-models/Tests/ShouldSucceed/try20.adl",
        "../ampersand-models/Tests/ShouldSucceed/try19.adl",
        "../ampersand-models/Tests/ShouldSucceed/try15.adl",
        "../ampersand-models/Tests/ShouldSucceed/try14.adl",
        "../ampersand-models/Tests/ShouldSucceed/try13b.adl",
        "../ampersand-models/Tests/ShouldSucceed/try13.adl",
        "../ampersand-models/Tests/ShouldSucceed/try12.adl",
        "../ampersand-models/Tests/ShouldSucceed/try10.adl",
        "../ampersand-models/Tests/ShouldSucceed/Ticket398.adl",
        "../ampersand-models/Tests/ShouldSucceed/SelectExprTest.adl",
        "../ampersand-models/Tests/ShouldSucceed/residutest.adl",
        "../ampersand-models/Tests/ShouldSucceed/propertytests.adl",
        "../ampersand-models/Tests/ShouldSucceed/InterfaceTest4.adl",
        "../ampersand-models/Tests/ShouldSucceed/InterfaceTest1.adl",
        "../ampersand-models/Tests/ShouldSucceed/FlipPHPBug.adl",
        "../ampersand-models/Tests/ShouldSucceed/EscapeTest.adl",
        "../ampersand-models/Tests/ShouldSucceed/ClassyInterfaces.adl",
        "../ampersand-models/Tests/ShouldSucceed/CheckDanglingPurposes.adl",
        "../ampersand-models/Tests/ShouldSucceed/Bug435.adl",
        "../ampersand-models/Tests/ShouldSucceed/ASTbugje.adl",
        "../ampersand-models/Tests/ShouldSucceed/ARM-Test12.adl",
        "../ampersand-models/Tests/ShouldSucceed/Archimate1.adl",
        "../ampersand-models/Ticket380/CSA_StatusRules.adl",
        "../ampersand-models/Ticket380/CSA_Op.adl",
        "../ampersand-models/Ticket380/CSA_Op Status.adl",
        "../ampersand-models/Ticket380/CSA_Op Ontology.adl",
        "../ampersand-models/Ticket380/CSA_Ontology_Process.adl",
        "../ampersand-models/Ticket380/CSA_Ontology_ExecEngine.adl",
        "../ampersand-models/Ticket380/CSA_Ontology.adl",
        "../ampersand-models/Ticket394/CSA_Op.adl",
        "../ampersand-models/Ticket394/CSA_Op Status.adl",
        "../ampersand-models/Ticket394/CSA_Op Process.adl",
        "../ampersand-models/Ticket394/CSA_Op Ontology.adl",
        "../ampersand-models/VIRO/strippedFsVIROENG.adl",
        "../ampersand-models/VOGDemo/VOGAanvraag.adl",
        "../ampersand-models/VOGDemo/StrafbladKoppeling.adl",
        "../ampersand-models/VOGDemo/PortalenInloggen.adl",
        "../ampersand-models/VOGDemo/Identificatiemiddelen.adl",
        "../ampersand-models/VOGDemo/Handelsregister.adl",
        "../ampersand-models/VOGDemo/GBA.adl",
        "../ampersand-models/VOGDemo/DEMO_VOG.adl",
        "../ampersand-models/VOGDemo/BasisDatatypes.adl",
        "../ampersand-models/VOGDemo2/VOGExecEngine.adl",
        "../ampersand-models/VOGDemo2/VOGAanvraag.adl",
        "../ampersand-models/VOGDemo2/StrafbladKoppeling.adl",
        "../ampersand-models/VOGDemo2/Identificatiemiddelen.adl",
        "../ampersand-models/VOGDemo2/Handelsregister.adl",
        "../ampersand-models/VOGDemo2/GBA.adl",
        "../ampersand-models/VOGDemo2/DEMO_VOG.adl",
        "../ampersand-models/VOGDemo2/BasisDatatypes.adl",
        "../ampersand-models/Webshop/Webshop.adl" ]

scripts :: IO [FilePath]
scripts =
     do fs <- getFiles ".adl" "ArchitectureAndDesign"
        ds <- getFiles ".adl" "AmpersandData/FormalAmpersand"
        return $ models ++ fs ++ ds
