{-# LANGUAGE Rank2Types, NoMonomorphismRestriction, ScopedTypeVariables #-}
module Database.Design.Ampersand.Test.TestScripts (getTestScripts) where
import System.Directory
import Control.Monad
import Data.List(sort)

endswith :: String -> String -> Bool
endswith a b = drop (length a - length b) a == b

-- Returns tuple with files and subdirectories inside the given directory
getDirectory :: FilePath -> IO ([FilePath],[FilePath])
getDirectory path =
    do contents <- getDirectoryContents path
       let valid = filter (\x-> x /= "." && x /= "..") contents
       let paths = map (path ++) valid
       files <- filterM doesFileExist paths
       subdirs <- filterM doesDirectoryExist paths
       return (sort files, sort subdirs)

getFiles :: String -> FilePath -> IO [FilePath]
getFiles ext dir =
    do (fs, ds) <- getDirectory (dir++"/")
       let files = filter (`endswith` ext) fs
       foldM recursive files ds
      where recursive rs d =
                do ms <- getFiles ext d
                   return $ ms ++ rs

models :: [FilePath]
models = [  "../ampersand-models/Atlasv2/RepoRap/Fspec.adl"
         , "../ampersand-models/Bugs/Current/Other/Bug335_Kl0Kl1.adl"
         , "../ampersand-models/Bugs/Current/SQL/ARM20-Test8.adl"
         , "../ampersand-models/Bugs/Current/SQLFail/Bug331_TotalInjective.adl"
         , "../ampersand-models/Bugs/Current/SQLFail/Bug302_IgnoredV.adl"
         , "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/WBP-Glossary.adl"
         , "../ampersand-models/Bugs/Current MultiFile/Bug388_Retina/RETINABUG.adl"
         , "../ampersand-models/Bugs/Fixed/Other/Bug_GeneratedTables.adl"
         , "../ampersand-models/Bugs/Fixed/Other/Bug_ColumnProperties.adl"
         , "../ampersand-models/Bugs/Fixed/SQL/Bug_Totality.adl"
         , "../ampersand-models/Bugs/Fixed/SQL/Bug_SingletonExpression.adl"
         , "../ampersand-models/Bugs/Fixed/SQL/Bug_RelAdd.adl"
         , "../ampersand-models/Bugs/Fixed/SQL/Bug_HaskellViolationTest.adl"
         , "../ampersand-models/Bugs/No Sentinel/TechDataModelTest.adl"
         , "../ampersand-models/Bugs/No Sentinel/Bug434.adl"
         , "../ampersand-models/Bugs/No Sentinel/Bug337_FatalONE.adl"
         , "../ampersand-models/Delivery/IdentiSample.adl"
         , "../ampersand-models/Delivery/DeliverySessions.adl"
         , "../ampersand-models/Delivery/DeliveryRieksObl.adl"
         , "../ampersand-models/Delivery/DeliveryRieksNoObl.adl"
         , "../ampersand-models/Delivery/DeliveryAccounts.adl"
         , "../ampersand-models/Delivery/Delivery.adl"
         , "../ampersand-models/FPA/FPATest.adl"
         , "../ampersand-models/Generics/GenericYesNo.adl"
         , "../ampersand-models/Generics/GenericTransitiveClosure.adl"
         , "../ampersand-models/Generics/GenericSessionAccounts.adl"
         , "../ampersand-models/Generics/Generics.adl"
         , "../ampersand-models/Generics/GenericDateTime.adl"
         , "../ampersand-models/HRM/HRM Ontology.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/wettelijkeTaken.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/Producten.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/Gebeurtenissen.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/uitgangslijstjes/BusinessInterfaces.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/versies/Taken.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/versies/RfPtje.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/wetsteksten.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/VIROarch.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/Populaties.adl"
         , "../ampersand-models/INDOORS/overzichten/uitgangsscripts/Handelingen.adl"
         , "../ampersand-models/INDOORS/Gebeurtenis.adl"
         , "../ampersand-models/INDOORS/DemoLamicieCode105.adl"
         , "../ampersand-models/Inspectie OCW/OCWdemo/Voorschriften.adl"
         , "../ampersand-models/ISTAR/ISTAR.adl"
         , "../ampersand-models/ISTAR/ISTAR-Workshop.adl"
         , "../ampersand-models/ISTAR/GenericDataTypes.adl"
         , "../ampersand-models/Misc/Kernmodel.adl"
         , "../ampersand-models/Misc/Hello.adl"
         , "../ampersand-models/Misc/FraakTest2.adl"
         , "../ampersand-models/Misc/FraakTest1.adl"
         , "../ampersand-models/Misc/ARM20-Test8.adl"
         , "../ampersand-models/Misc/ARM20-Test6.adl"
         , "../ampersand-models/Misc/ARM20-Test5.adl"
         , "../ampersand-models/Misc/ARM20-Test4.adl"
         , "../ampersand-models/Misc/ARM20-Test3.adl"
         , "../ampersand-models/Misc/ARM20-Test2.adl"
         , "../ampersand-models/Misc/ARM20-Test1.adl"
         , "../ampersand-models/Misc/ARM-Test2.adl"
         , "../ampersand-models/Misc/ARM-Test1.adl"
         , "../ampersand-models/Misc/ArchiTest5.adl"
         , "../ampersand-models/Misc/ArchiTest4.adl"
         , "../ampersand-models/Misc/ArchiTest3.adl"
         , "../ampersand-models/NVWA DTV/Urenpools.adl"
         , "../ampersand-models/NVWA DTV/Tijdverantwoordingen.adl"
         , "../ampersand-models/NVWA DTV/Periodeverantwoordingen.adl"
         , "../ampersand-models/NVWA DTV/OnregelmatigeDiensten.adl"
         , "../ampersand-models/NVWA DTV/Onderbrekingen.adl"
         , "../ampersand-models/NVWA DTV/Login.adl"
         , "../ampersand-models/NVWA DTV/Kennismotor.adl"
         , "../ampersand-models/NVWA DTV/expTijdsduur.adl"
         , "../ampersand-models/NVWA DTV/DTV.adl"
         , "../ampersand-models/RAPRelatedPatterns/UIservices.adl"
         , "../ampersand-models/ServiceDesk/case.adl"
         --, "../ampersand-models/Session/Session.adl"
         , "../ampersand-models/Simple/DeliverySimpleOPA.adl"
         , "../ampersand-models/Simple/DeliverySimple.adl"
         , "../ampersand-models/Simple/Delivery.adl"
         , "../ampersand-models/Tests/NoSentinel/Multiplicities.adl"
         , "../ampersand-models/Tests/ShouldFail/Try48.adl"
         --, "../ampersand-models/Tests/ShouldFail/Session.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try9.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try52.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try51.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try50.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try46.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try45.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try43a.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try42.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try41a.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try41.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try40.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try39.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try38.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try37.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try35.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try34.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try33.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Try32.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try31.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try30.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try29.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try28.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try22.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try21.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try20.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try19.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try15.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try14.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try13b.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try13.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try12.adl"
         , "../ampersand-models/Tests/ShouldSucceed/try10.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Ticket398.adl"
         , "../ampersand-models/Tests/ShouldSucceed/SelectExprTest.adl"
         , "../ampersand-models/Tests/ShouldSucceed/residutest.adl"
         , "../ampersand-models/Tests/ShouldSucceed/propertytests.adl"
         , "../ampersand-models/Tests/ShouldSucceed/InterfaceTest4.adl"
         , "../ampersand-models/Tests/ShouldSucceed/InterfaceTest1.adl"
         , "../ampersand-models/Tests/ShouldSucceed/FlipPHPBug.adl"
         , "../ampersand-models/Tests/ShouldSucceed/EscapeTest.adl"
         , "../ampersand-models/Tests/ShouldSucceed/ClassyInterfaces.adl"
         , "../ampersand-models/Tests/ShouldSucceed/CheckDanglingPurposes.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Bug435.adl"
         , "../ampersand-models/Tests/ShouldSucceed/ASTbugje.adl"
         , "../ampersand-models/Tests/ShouldSucceed/ARM-Test12.adl"
         , "../ampersand-models/Tests/ShouldSucceed/Archimate1.adl"
         , "../ampersand-models/Ticket380/CSA_Op Ontology.adl"
         , "../ampersand-models/Ticket380/CSA_Ontology.adl"
         , "../ampersand-models/Ticket394/CSA_Op.adl"
         , "../ampersand-models/Ticket394/CSA_Op Ontology.adl"
         , "../ampersand-models/VIRO/strippedFsVIROENG.adl"
         , "../ampersand-models/VOGDemo/StrafbladKoppeling.adl"
         , "../ampersand-models/VOGDemo/Identificatiemiddelen.adl"
         , "../ampersand-models/VOGDemo/Handelsregister.adl"
         , "../ampersand-models/VOGDemo/GBA.adl"
         , "../ampersand-models/VOGDemo/DEMO_VOG.adl"
         , "../ampersand-models/VOGDemo/BasisDatatypes.adl"
         , "../ampersand-models/VOGDemo2/StrafbladKoppeling.adl"
         , "../ampersand-models/VOGDemo2/Identificatiemiddelen.adl"
         , "../ampersand-models/VOGDemo2/Handelsregister.adl"
         , "../ampersand-models/VOGDemo2/BasisDatatypes.adl"
         , "../ampersand-models/Webshop/Webshop.adl"
         ]

getTestScripts :: IO [FilePath]
getTestScripts =
     do fs <- getFiles ".adl" "ArchitectureAndDesign"
        ds <- return[] -- getFiles ".adl" "AmpersandData/FormalAmpersand"
        return $ fs ++ ds ++ models
