# This workflow builds and pushes Ampersand images to Docker Hub
# We want to have images for branches 'master' (latest) and 'development' and for all tags (i.e. releases, like e.g. v4.0.2)
# We use a Github Action from the market place. See: https://github.com/marketplace/actions/build-and-push-docker-images
name: Build push to Docker Hub
on:
  push:
    branches: # empty list to trigger all branches
    - master
    tags:
    - 'v*'

jobs:
  build-push:
    name: Build push
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ampersandtarski/ampersand
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }} # see meta step above
        labels: ${{ steps.meta.outputs.labels }}
