# This file is inspired by the blogpost at https://kodimensional.dev/github-actions
# The purpose of this workflow is to build the ampersand generator in all 3 major platforms,
# and to run the regression testcases on them. 

name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: 
      - '**' # Only trigger on branches (i.e. not tags, ..)

jobs:

  build-and-test-with-stack:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        plan:
        - { build: stack, resolver: "--resolver lts-17.9"  }   # ghc-8.10.4

    name: ${{ matrix.plan.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1.4
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
# TODO: Cache might be done better, see for inspiration:  https://github.com/godu/advent-of-code-2020/blob/46796832f59d185457a8edf8de043a54a451d688/.github/workflows/ci.yml
      with:
        path: | 
          ~/.ghc
          ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: SetPath-ubuntu
      if: ${{ runner.os == 'ubuntu' }}
      run : |
         echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: SetPath-windows
      if: ${{ runner.os == 'Windows' }}
      run : |
         echo "C:\Users\runneradmin\AppData\Roaming\local\bin" >> $GITHUB_PATH
    - name: SetPath-macOS
      if: ${{ runner.os == 'macOS' }}
      run : |
         echo "/Users/runner/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack install --system-ghc --test --bench --no-run-tests --no-run-benchmarks --flag ampersand:buildAll

#    - name: Test
#      if: ${{ runner.os == 'ubuntu' }}
#      run: |
#        stack test --system-ghc

    - name: get-version
      run: | 
        echo "::set-output name=version::$(ampersand --numeric-version)"
      id: version

    - name: Upload artifacts (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v2
      with:
        name: ampersand-${{ runner.os }}-binaries-${{ steps.get-version.outputs.version }}
        path: C:/Users/runneradmin/AppData/Roaming/local/bin/*
    - name: Upload artifacts (macOS)
      if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      uses: actions/upload-artifact@v2
      with:
        name: ampersand-${{ runner.os }}-binaries-${{ steps.get-version.outputs.version }}
        path: /Users/runner/.local/bin/*
    - name: Upload artifacts (ubuntu)
      if: ${{ runner.os == 'ubuntu' }}
      uses: actions/upload-artifact@v2
      with:
        name: ampersand-${{ runner.os }}-binaries-${{ steps.get-version.outputs.version }}
        path: /home/runner/.local/bin/*



  release:
    needs: build-and-test-with-stack
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ steps.get-version.outputs.version }}
        tag_name: ${{ github.ref }}
        body: |
          Here you find yet another release of Ampersand. Check out the [releasenotes](https://github.com/AmpersandTarski/Ampersand/blob/development/ReleaseNotes.md) to see what has changed. 
      env:
        GITHUB_TOKEN: ${{ github.token }}     

