# Inspired by https://tech.freckle.com/2021/05/18/haskell-on-actions/
name: Check Code Quality 👌
on:
  push:
    branches:
      - "**" # Only trigger on branches (i.e. not tags, ..)
    paths-ignore:
      - "docs/**" # If only documentation changes, no need to build.
jobs:
  hlint:
    name: Check for code sanity with hlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project contents 📡
        uses: actions/checkout@v3
      - name: Setup hlint
        uses: rwe/actions-hlint-setup
      - name: Run hlint
        uses: rwe/actions-hlint-run
  weeder:
    name: Check dead code with weeder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project contents 📡
        uses: actions/checkout@v3
      - name: Check weeds 🌿🌿🌿
        uses: freckle/stack-action
        with:
          test: false

      # Weeder needs compilation artifacts, so it must still be the same Job
      - uses: freckle/weeder-action
