name: Continuous Integration
on:
  push:
    branches: # empty list to only trigger on branches (i.e. not tags, ..)

env:
  DOCKER_AMPERSAND_IMAGE: ampersandtarski/ampersand
  DOCKER_AMPERSAND_IMAGE_DEV: ampersandtarski/ampersand:development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    # See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    # Because steps run in their own process, changes to environment variables are not preserved between steps
    steps:
    - name: Checkout repository
      uses: actions/checkout@master # this step reuses a default Github action; see: https://github.com/actions
    
    - name: Prepare for docker
      run: |
        echo Running on branch ${GITHUB_REF##*/}
        docker version
    
    - name: Pull dev image to use as cache
      run: docker pull ${DOCKER_AMPERSAND_IMAGE_DEV} || true
    
    # This step only builds the 'buildstage' stage (see `--target buildstage`)
    # See: https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/ to understand why we use --target and --cache-from here
    - name: Build buildstage
      run: docker build . --cache-from ${DOCKER_AMPERSAND_IMAGE_DEV} --target buildstage --tag ${DOCKER_AMPERSAND_IMAGE}:${GITHUB_REF##*/} --build-arg GIT_SHA=${{ github.sha }} --build-arg GIT_Branch=${{ github.ref }}
    
    # This step build the final (slim) image 
    - name: Build final image
      run: docker build . --cache-from ${DOCKER_AMPERSAND_IMAGE}:${GITHUB_REF##*/} --tag ${DOCKER_AMPERSAND_IMAGE}:latest --build-arg GIT_SHA=${{ github.sha }} --build-arg GIT_Branch=${{ github.ref }}
