name: Continuous Integration
on:
  push:
    branches: # empty list to only trigger on branches (i.e. not tags, ..)

env:
  DOCKER_AMPERSAND_IMAGE: ampersandtarski/ampersand

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    # See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    # Because steps run in their own process, changes to environment variables are not preserved between steps
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Prepare for docker
      run: |
        echo Running on branch ${GITHUB_REF##*/}
        docker version
    
    # This step build the final (slim) image 
    - name: Build final image
      run: docker build . --tag ${DOCKER_AMPERSAND_IMAGE}:latest --build-arg GIT_SHA=${{ github.sha }} --build-arg GIT_Branch=${{ github.ref }}
