# This workflow intends to run the regression test of Ampersand. This used
# to be done using Travis-ci, but now we only use github actions for all these
# job automation.
name: regression-test

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.10', '8.8', '8.6']
        include:
        - os: windows-latest
          ghc: '8.6' # Every later version segfaults a lot :(
        - os: macOS-latest

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
    - run: cabal v2-freeze --enable-tests
    - uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
 
  