# Workflow to update documentation on our landingpage AmpersandTarski.gihub.io
name: Trigger Documentation Update

on:
  push:
    branches:
      - main
      - documentation
    paths:
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Trigger the "DeployToPages" workflow in the "AmpersandTarski.github.io" repository
      - run: |
          curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" -H \
          "Content-Type: application/json" https://api.github.com/repos/AmpersandTarski/AmpersandTarski.github.io/actions/workflows/DeployToPages.yml/dispatches \
          --data '{"ref": "main"}'
